- name: Install 'bash'
  become: true
  ansible.builtin.package:
    name: bash
    state: present

- name: Ensure required directories exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/{{ item }}"
    state: directory
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0755"
  loop:
    - .bashrc.d

- name: Deploy configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ target_user_info.home }}/{{ item }}"
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0644"
  loop:
    - ".bashrc"
    - ".bash_profile"
