- name: Base CLI | fish | Mark 'fish' to be installed
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['fish'] }}"

- name: Base CLI | fish | Mark 'hostname' to be installed (Ubuntu, Fedora)
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['hostname'] }}"
  when: "ansible_distribution in ['Ubuntu', 'Fedora']"

- name: Base CLI | fish | Mark 'inetutils' to be installed (Ubuntu, Fedora)
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['inetutils'] }}"
  when: "ansible_distribution in ['Archlinux']"

- name: Base CLI | fish | Ensure 'uptime' is installed (Fedora)
  become: yes
  ansible.builtin.package:
    name: procps-ng
    state: present
  when: "ansible_distribution in ['Fedora']"

- name: Base CLI | fish | Ensure 'fish' directories exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/.config/fish/{{ item }}/"
    state: directory
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0755"
  loop:
    - conf.d
    - functions

- name: Base CLI | fish | Deploy custom 'fish' functions
  ansible.builtin.copy:
    src: "fish/{{ item }}"
    dest: "{{ target_user_info.home }}/{{ item }}"
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0644"
  loop:
    - .config/fish/functions/fish_prompt.fish
    - .config/fish/functions/fish_greeting.fish

- name: Base CLI | fish | Deploy 'fish' starter for 'bash'
  ansible.builtin.copy:
    src: fish/.bashrc.d/99-launch-fish.sh
    dest: "{{ target_user_info.home }}/.bashrc.d/99-launch-fish.sh"
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0644"
