- name: Base CLI | fish | Mark 'fish' to be installed
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['fish'] }}"

- name: Base CLI | fish | Mark 'hostname' to be installed (Ubuntu, Fedora)
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['hostname'] }}"
  when: "ansible_distribution in ['Ubuntu', 'Fedora']"

- name: Base CLI | fish | Mark 'inetutils' to be installed (Ubuntu, Fedora)
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['inetutils'] }}"
  when: "ansible_distribution in ['Archlinux']"

- name: Base CLI | fish | Mark 'uptime' to be installed (Fedora)
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + ['procps-ng'] }}"
  when: "ansible_distribution in ['Fedora']"

- name: Base CLI | fish | Ensure required directories exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/{{ item }}"
    state: directory
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0755"
  loop:
    - .config/fish/conf.d/
    - .config/fish/functions/

- name: Base CLI | fish | Deploy configuration files
  ansible.builtin.copy:
    src: "fish/{{ item }}"
    dest: "{{ target_user_info.home }}/{{ item }}"
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0644"
  loop:
    - .bashrc.d/99-launch-fish.sh
    - .config/fish/functions/fish_prompt.fish
    - .config/fish/functions/fish_greeting.fish
