- name: Base CLI | bash
  ansible.builtin.include_tasks: ./bash.yml

- name: Base CLI | fish
  ansible.builtin.include_tasks: ./fish.yml

- name: Base CLI | eza
  ansible.builtin.include_tasks: ./eza.yml
