- name: Base CLI | Initialize package list
  ansible.builtin.set_fact:
    setup_base_cli_packages: []
  tags:
    - always

- name: Base CLI | Configure shells
  ansible.builtin.include_tasks: "./{{ shell_task }}.yml"
  loop:
    - fish
    - tmux
  loop_control:
    loop_var: shell_task

- name: Base CLI | Configure CLI tools alternatives
  ansible.builtin.include_tasks: "./{{ cli_tools_alternatives_task }}.yml"
  loop:
    - bat_migrations
    - bat
    - fd
    - eza
    - ripgrep
  loop_control:
    loop_var: cli_tools_alternatives_task

- name: Base CLI | Configure editors
  ansible.builtin.include_tasks: "./{{ editor_task }}.yml"
  loop:
    - neovim
  loop_control:
    loop_var: editor_task

- name: Base CLI | Configure system monitoring and administration tools
  ansible.builtin.include_tasks: "./{{ system_admin_tools_task }}.yml"
  loop:
    - btop
  loop_control:
    loop_var: system_admin_tools_task

- name: Base CLI | Install all base packages
  become: true
  ansible.builtin.package:
    name: "{{ setup_base_cli_packages | unique }}"
    state: present
  when: setup_base_cli_packages | length > 0
  tags:
    - always
