- name: Base CLI | Initialize package list
  ansible.builtin.set_fact:
    packages_to_install: []
  tags:
    - always

- name: Base CLI | bash
  ansible.builtin.include_tasks: ./bash.yml

- name: Base CLI | fish
  ansible.builtin.include_tasks: ./fish.yml

- name: Base CLI | tmux
  ansible.builtin.include_tasks: ./tmux.yml

- name: Base CLI | eza
  ansible.builtin.include_tasks: ./eza.yml

- name: Base CLI | bat
  ansible.builtin.include_tasks: ./bat.yml

- name: Base CLI | fd
  ansible.builtin.include_tasks: ./fd.yml

- name: Base CLI | ripgrep
  ansible.builtin.include_tasks: ./ripgrep.yml

- name: Base CLI | btop
  ansible.builtin.include_tasks: ./btop.yml

- name: Base CLI | Install all base packages
  become: yes
  ansible.builtin.package:
    name: "{{ packages_to_install | unique }}"
    state: present
  when: packages_to_install | length > 0
  tags:
    - always
