- name: Base CLI | tmux | Ensure 'tmux' is installed
  become: yes
  ansible.builtin.package:
    name: tmux
    state: present

- name: Base CLI | tmux | Ensure `$HOME/.config/tmux/` directory exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/.config/tmux/"
    state: directory
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: '0755'

- name: Base CLI | tmux | Deploy '$HOME/.config/tmux/tmux.conf'
  ansible.builtin.copy:
    src: tmux/.config/tmux/tmux.conf
    dest: "{{ target_user_info.home }}/.config/tmux/tmux.conf"
    owner: "{{ target_user_info.name }}"
    group: "{{ target_user_info.name }}"
    mode: "0644"
