- name: "Gather facts about the target user ({{ setup_shell_user }})"
  ansible.builtin.user:
    name: "{{ setup_shell_user }}"
  register: target_user_info
  check_mode: true

- name: Ensure bash and fish are installed
  become: yes
  ansible.builtin.package:
    name: "{{ setup_shell_packages_by_distro[ansible_distribution] }}"
    state: present

- name: "Set fish as the default interactive shell for {{ setup_shell_user }}"
  become: yes
  ansible.builtin.user:
    name: "{{ setup_shell_user }}"
    shell: /usr/bin/fish

- name: Deploy .bashrc for {{ setup_shell_user }}
  ansible.builtin.template:
    src: bashrc.j2
    dest: "{{ target_user_info.home }}/.bashrc"
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: "0644"

- name: Ensure .bashrc.d directory exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/.bashrc.d"
    state: directory
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: '0755'

- name: Ensure .config/fish directory exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/.config/fish"
    state: directory
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: '0755'

- name: Ensure .config/fish/conf.d directory exists
  ansible.builtin.file:
    path: "{{ target_user_info.home }}/.config/fish/conf.d"
    state: directory
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: '0755'

- name: Deploy static fish configurations
  ansible.builtin.copy:
    src: .config/fish/
    dest: "{{ target_user_info.home }}/.config/fish/"
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: "0644"
    directory_mode: "0755"

- name: Deploy config.fish for {{ setup_shell_user }}
  ansible.builtin.template:
    src: config.fish.j2
    dest: "{{ target_user_info.home }}/.config/fish/config.fish"
    owner: "{{ setup_shell_user }}"
    group: "{{ setup_shell_user }}"
    mode: "0644"
