galaxy_info:
  role_name: fish
  namespace: system_forger
  author: DrOptix
  description: >
    Extends shell configuration for Linux systems by setting up 'fish' as
    interactive shell.
  license: MIT
  min_ansible_version: "2.10"

dependencies:
  - bash
