---
- name: WSL
  hosts: localhost
  become: yes

  vars:
    target_user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: "Pre-Tasks | Gather facts about user \"{{ target_user }}\""
      ansible.builtin.user:
        name: "{{ target_user }}"
      register: target_user_info
      check_mode: true

    - name: "Pre-Tasks | Fail if target user '{{ target_user }}' does not exist"
      ansible.builtin.fail:
        msg: "Target user '{{ target_user }}' does not exist on this system."
      when: not target_user_info

  roles:
    - role: setup_base_cli
